export const COUNTRIES = [
  { title: "Afghanistan", value: "AF", code: "93" },
  { title: "Angola", value: "AO", code: "244" },
  { title: "Albania", value: "AL", code: "355" },
  { title: "Andorra", value: "AD", code: "376" },
  { title: "United Arab Emirates", value: "AE", code: "971" },
  { title: "Argentina", value: "AR", code: "54" },
  { title: "Armenia", value: "AM", code: "374" },
  { title: "Antigua and Barbuda", value: "AG", code: "1268" },
  { title: "Australia", value: "AU", code: "61" },
  { title: "Austria", value: "AT", code: "43" },
  { title: "Azerbaijan", value: "AZ", code: "994" },
  { title: "Burundi", value: "BI", code: "257" },
  { title: "Belgium", value: "BE", code: "32" },
  { title: "Benin", value: "BJ", code: "229" },
  { title: "Burkina Faso", value: "BF", code: "226" },
  { title: "Bangladesh", value: "BD", code: "880" },
  { title: "Bulgaria", value: "BG", code: "359" },
  { title: "Bahrain", value: "BH", code: "973" },
  { title: "Bahamas", value: "BS", code: "1242" },
  { title: "Bosnia and Herzegovina", value: "BA", code: "387" },
  { title: "Belarus", value: "BY", code: "375" },
  { title: "Belize", value: "BZ", code: "501" },
  { title: "Bolivia", value: "BO", code: "591" },
  { title: "Brazil", value: "BR", code: "55" },
  { title: "Barbados", value: "BB", code: "1246" },
  { title: "Brunei", value: "BN", code: "673" },
  { title: "Bhutan", value: "BT", code: "975" },
  { title: "Botswana", value: "BW", code: "267" },
  { title: "Central African Republic", value: "CF", code: "236" },
  { title: "Canada", value: "CA", code: "1" },
  { title: "Switzerland", value: "CH", code: "41" },
  { title: "Chile", value: "CL", code: "56" },
  { title: "China", value: "CN", code: "86" },
  { title: "Ivory Coast", value: "CI", code: "225" },
  { title: "Cameroon", value: "CM", code: "237" },
  { title: "DR Congo", value: "CD", code: "243" },
  { title: "Republic of the Congo", value: "CG", code: "242" },
  { title: "Colombia", value: "CO", code: "57" },
  { title: "Comoros", value: "KM", code: "269" },
  { title: "Cape Verde", value: "CV", code: "238" },
  { title: "Costa Rica", value: "CR", code: "506" },
  { title: "Cuba", value: "CU", code: "53" },
  { title: "Cyprus", value: "CY", code: "357" },
  { title: "Czechia", value: "CZ", code: "420" },
  { title: "Germany", value: "DE", code: "49" },
  { title: "Djibouti", value: "DJ", code: "253" },
  { title: "Dominica", value: "DM", code: "1767" },
  { title: "Denmark", value: "DK", code: "45" },
  { title: "Dominican Republic", value: "DO", code: "1809" },
  { title: "Algeria", value: "DZ", code: "213" },
  { title: "Ecuador", value: "EC", code: "593" },
  { title: "Egypt", value: "EG", code: "20" },
  { title: "Eritrea", value: "ER", code: "291" },
  { title: "Spain", value: "ES", code: "34" },
  { title: "Estonia", value: "EE", code: "372" },
  { title: "Ethiopia", value: "ET", code: "251" },
  { title: "Finland", value: "FI", code: "358" },
  { title: "Fiji", value: "FJ", code: "679" },
  { title: "France", value: "FR", code: "33" },
  { title: "Micronesia", value: "FM", code: "691" },
  { title: "Gabon", value: "GA", code: "241" },
  { title: "United Kingdom", value: "GB", code: "44" },
  { title: "Georgia", value: "GE", code: "995" },
  { title: "Ghana", value: "GH", code: "233" },
  { title: "Guinea", value: "GN", code: "224" },
  { title: "Gambia", value: "GM", code: "220" },
  { title: "Guinea-Bissau", value: "GW", code: "245" },
  { title: "Equatorial Guinea", value: "GQ", code: "240" },
  { title: "Greece", value: "GR", code: "30" },
  { title: "Grenada", value: "GD", code: "1473" },
  { title: "Guatemala", value: "GT", code: "502" },
  { title: "Guyana", value: "GY", code: "592" },
  { title: "Honduras", value: "HN", code: "504" },
  { title: "Croatia", value: "HR", code: "385" },
  { title: "Haiti", value: "HT", code: "509" },
  { title: "Hungary", value: "HU", code: "36" },
  { title: "Indonesia", value: "ID", code: "62" },
  { title: "India", value: "IN", code: "91" },
  { title: "Ireland", value: "IE", code: "353" },
  {
    title: "Iran",
    value: "IR",
    code: "98",
  },
  {
    title: "Iraq",
    value: "IQ",
    code: "964",
  },
  {
    title: "Iceland",
    value: "IS",
    code: "354",
  },
  {
    title: "Israel",
    value: "IL",
    code: "972",
  },
  {
    title: "Italy",
    value: "IT",
    code: "39",
  },
  {
    title: "Jamaica",
    value: "JM",
    code: "1876",
  },
  {
    title: "Jordan",
    value: "JO",
    code: "962",
  },
  {
    title: "Japan",
    value: "JP",
    code: "81",
  },
  {
    title: "Kazakhstan",
    value: "KZ",
    code: "76",
  },
  {
    title: "Kenya",
    value: "KE",
    code: "254",
  },
  {
    title: "Kyrgyzstan",
    value: "KG",
    code: "996",
  },
  {
    title: "Cambodia",
    value: "KH",
    code: "855",
  },
  {
    title: "Kiribati",
    value: "KI",
    code: "686",
  },
  {
    title: "Saint Kitts and Nevis",
    value: "KN",
    code: "1869",
  },
  {
    title: "South Korea",
    value: "KR",
    code: "82",
  },
  {
    title: "Kuwait",
    value: "KW",
    code: "965",
  },
  {
    title: "Laos",
    value: "LA",
    code: "856",
  },
  {
    title: "Lebanon",
    value: "LB",
    code: "961",
  },
  {
    title: "Liberia",
    value: "LR",
    code: "231",
  },
  {
    title: "Libya",
    value: "LY",
    code: "218",
  },
  {
    title: "Saint Lucia",
    value: "LC",
    code: "1758",
  },
  {
    title: "Liechtenstein",
    value: "LI",
    code: "423",
  },
  {
    title: "Sri Lanka",
    value: "LK",
    code: "94",
  },
  {
    title: "Lesotho",
    value: "LS",
    code: "266",
  },
  {
    title: "Lithuania",
    value: "LT",
    code: "370",
  },
  {
    title: "Luxembourg",
    value: "LU",
    code: "352",
  },
  {
    title: "Latvia",
    value: "LV",
    code: "371",
  },
  {
    title: "Morocco",
    value: "MA",
    code: "212",
  },
  {
    title: "Monaco",
    value: "MC",
    code: "377",
  },
  {
    title: "Moldova",
    value: "MD",
    code: "373",
  },
  {
    title: "Madagascar",
    value: "MG",
    code: "261",
  },
  {
    title: "Maldives",
    value: "MV",
    code: "960",
  },
  {
    title: "Mexico",
    value: "MX",
    code: "52",
  },
  {
    title: "Marshall Islands",
    value: "MH",
    code: "692",
  },
  {
    title: "Macedonia",
    value: "MK",
    code: "389",
  },
  {
    title: "Mali",
    value: "ML",
    code: "223",
  },
  {
    title: "Malta",
    value: "MT",
    code: "356",
  },
  {
    title: "Myanmar",
    value: "MM",
    code: "95",
  },
  {
    title: "Montenegro",
    value: "ME",
    code: "382",
  },
  {
    title: "Mongolia",
    value: "MN",
    code: "976",
  },
  {
    title: "Mozambique",
    value: "MZ",
    code: "258",
  },
  {
    title: "Mauritania",
    value: "MR",
    code: "222",
  },
  {
    title: "Mauritius",
    value: "MU",
    code: "230",
  },
  {
    title: "Malawi",
    value: "MW",
    code: "265",
  },
  {
    title: "Malaysia",
    value: "MY",
    code: "60",
  },
  {
    title: "Namibia",
    value: "NA",
    code: "264",
  },
  {
    title: "Niger",
    value: "NE",
    code: "227",
  },
  {
    title: "Nigeria",
    value: "NG",
    code: "234",
  },
  {
    title: "Nicaragua",
    value: "NI",
    code: "505",
  },
  {
    title: "Netherlands",
    value: "NL",
    code: "31",
  },
  {
    title: "Norway",
    value: "NO",
    code: "47",
  },
  {
    title: "Nepal",
    value: "NP",
    code: "977",
  },
  {
    title: "Nauru",
    value: "NR",
    code: "674",
  },
  {
    title: "New Zealand",
    value: "NZ",
    code: "64",
  },
  {
    title: "Oman",
    value: "OM",
    code: "968",
  },
  {
    title: "Pakistan",
    value: "PK",
    code: "92",
  },
  {
    title: "Panama",
    value: "PA",
    code: "507",
  },
  {
    title: "Peru",
    value: "PE",
    code: "51",
  },
  {
    title: "Philippines",
    value: "PH",
    code: "63",
  },
  {
    title: "Palau",
    value: "PW",
    code: "680",
  },
  {
    title: "Papua New Guinea",
    value: "PG",
    code: "675",
  },
  {
    title: "Poland",
    value: "PL",
    code: "48",
  },
  {
    title: "North Korea",
    value: "KP",
    code: "850",
  },
  {
    title: "Portugal",
    value: "PT",
    code: "351",
  },
  {
    title: "Paraguay",
    value: "PY",
    code: "595",
  },
  {
    title: "Qatar",
    value: "QA",
    code: "974",
  },
  {
    title: "Romania",
    value: "RO",
    code: "40",
  },
  {
    title: "Russia",
    value: "RU",
    code: "7",
  },
  {
    title: "Rwanda",
    value: "RW",
    code: "250",
  },
  {
    title: "Saudi Arabia",
    value: "SA",
    code: "966",
  },
  {
    title: "Sudan",
    value: "SD",
    code: "249",
  },
  {
    title: "Senegal",
    value: "SN",
    code: "221",
  },
  {
    title: "Singapore",
    value: "SG",
    code: "65",
  },
  {
    title: "Solomon Islands",
    value: "SB",
    code: "677",
  },
  {
    title: "Sierra Leone",
    value: "SL",
    code: "232",
  },
  {
    title: "El Salvador",
    value: "SV",
    code: "503",
  },
  {
    title: "San Marino",
    value: "SM",
    code: "378",
  },
  {
    title: "Somalia",
    value: "SO",
    code: "252",
  },
  {
    title: "Serbia",
    value: "RS",
    code: "381",
  },
  {
    title: "South Sudan",
    value: "SS",
    code: "211",
  },
  {
    title: "São Tomé and Príncipe",
    value: "ST",
    code: "239",
  },
  {
    title: "Suriname",
    value: "SR",
    code: "597",
  },
  {
    title: "Slovakia",
    value: "SK",
    code: "421",
  },
  {
    title: "Slovenia",
    value: "SI",
    code: "386",
  },
  {
    title: "Sweden",
    value: "SE",
    code: "46",
  },
  {
    title: "Swaziland",
    value: "SZ",
    code: "268",
  },
  {
    title: "Seychelles",
    value: "SC",
    code: "248",
  },
  {
    title: "Syria",
    value: "SY",
    code: "963",
  },
  {
    title: "Chad",
    value: "TD",
    code: "235",
  },
  {
    title: "Togo",
    value: "TG",
    code: "228",
  },
  {
    title: "Thailand",
    value: "TH",
    code: "66",
  },
  {
    title: "Tajikistan",
    value: "TJ",
    code: "992",
  },
  {
    title: "Turkmenistan",
    value: "TM",
    code: "993",
  },
  {
    title: "Timor-Leste",
    value: "TL",
    code: "670",
  },
  {
    title: "Tonga",
    value: "TO",
    code: "676",
  },
  {
    title: "Trinidad and Tobago",
    value: "TT",
    code: "1868",
  },
  {
    title: "Tunisia",
    value: "TN",
    code: "216",
  },
  {
    title: "Turkey",
    value: "TR",
    code: "90",
  },
  {
    title: "Tuvalu",
    value: "TV",
    code: "688",
  },
  {
    title: "Tanzania",
    value: "TZ",
    code: "255",
  },
  {
    title: "Uganda",
    value: "UG",
    code: "256",
  },
  {
    title: "Ukraine",
    value: "UA",
    code: "380",
  },
  {
    title: "Uruguay",
    value: "UY",
    code: "598",
  },
  {
    title: "United States",
    value: "US",
    code: "1",
  },
  {
    title: "Uzbekistan",
    value: "UZ",
    code: "998",
  },
  {
    title: "Vatican City",
    value: "VA",
    code: "3906698",
  },
  {
    title: "Saint Vincent and the Grenadines",
    value: "VC",
    code: "1784",
  },
  {
    title: "Venezuela",
    value: "VE",
    code: "58",
  },
  {
    title: "Vietnam",
    value: "VN",
    code: "84",
  },
  {
    title: "Vanuatu",
    value: "VU",
    code: "678",
  },
  {
    title: "Samoa",
    value: "WS",
    code: "685",
  },
  {
    title: "Yemen",
    value: "YE",
    code: "967",
  },
  {
    title: "South Africa",
    value: "ZA",
    code: "27",
  },
  {
    title: "Zambia",
    value: "ZM",
    code: "260",
  },
  {
    title: "Zimbabwe",
    value: "ZW",
    code: "263",
  },
];

export const countries = [
  { name: "Afghanistan", cca2: "AF", flag: "🇦🇫", code: "93" },
  { name: "Angola", cca2: "AO", flag: "🇦🇴", code: "244" },
  { name: "Albania", cca2: "AL", flag: "🇦🇱", code: "355" },
  { name: "Andorra", cca2: "AD", flag: "🇦🇩", code: "376" },
  { name: "United Arab Emirates", cca2: "AE", flag: "🇦🇪", code: "971" },
  { name: "Argentina", cca2: "AR", flag: "🇦🇷", code: "54" },
  { name: "Armenia", cca2: "AM", flag: "🇦🇲", code: "374" },
  { name: "Antigua and Barbuda", cca2: "AG", flag: "🇦🇬", code: "1268" },
  { name: "Australia", cca2: "AU", flag: "🇦🇺", code: "61" },
  { name: "Austria", cca2: "AT", flag: "🇦🇹", code: "43" },
  { name: "Azerbaijan", cca2: "AZ", flag: "🇦🇿", code: "994" },
  { name: "Burundi", cca2: "BI", flag: "🇧🇮", code: "257" },
  { name: "Belgium", cca2: "BE", flag: "🇧🇪", code: "32" },
  { name: "Benin", cca2: "BJ", flag: "🇧🇯", code: "229" },
  { name: "Burkina Faso", cca2: "BF", flag: "🇧🇫", code: "226" },
  { name: "Bangladesh", cca2: "BD", flag: "🇧🇩", code: "880" },
  { name: "Bulgaria", cca2: "BG", flag: "🇧🇬", code: "359" },
  { name: "Bahrain", cca2: "BH", flag: "🇧🇭", code: "973" },
  { name: "Bahamas", cca2: "BS", flag: "🇧🇸", code: "1242" },
  { name: "Bosnia and Herzegovina", cca2: "BA", flag: "🇧🇦", code: "387" },
  { name: "Belarus", cca2: "BY", flag: "🇧🇾", code: "375" },
  { name: "Belize", cca2: "BZ", flag: "🇧🇿", code: "501" },
  { name: "Bolivia", cca2: "BO", flag: "🇧🇴", code: "591" },
  { name: "Brazil", cca2: "BR", flag: "🇧🇷", code: "55" },
  { name: "Barbados", cca2: "BB", flag: "🇧🇧", code: "1246" },
  { name: "Brunei", cca2: "BN", flag: "🇧🇳", code: "673" },
  { name: "Bhutan", cca2: "BT", flag: "🇧🇹", code: "975" },
  { name: "Botswana", cca2: "BW", flag: "🇧🇼", code: "267" },
  { name: "Central African Republic", cca2: "CF", flag: "🇨🇫", code: "236" },
  { name: "Canada", cca2: "CA", flag: "🇨🇦", code: "1" },
  { name: "Switzerland", cca2: "CH", flag: "🇨🇭", code: "41" },
  { name: "Chile", cca2: "CL", flag: "🇨🇱", code: "56" },
  { name: "China", cca2: "CN", flag: "🇨🇳", code: "86" },
  { name: "Ivory Coast", cca2: "CI", flag: "🇨🇮", code: "225" },
  { name: "Cameroon", cca2: "CM", flag: "🇨🇲", code: "237" },
  { name: "DR Congo", cca2: "CD", flag: "🇨🇩", code: "243" },
  { name: "Republic of the Congo", cca2: "CG", flag: "🇨🇬", code: "242" },
  { name: "Colombia", cca2: "CO", flag: "🇨🇴", code: "57" },
  { name: "Comoros", cca2: "KM", flag: "🇰🇲", code: "269" },
  { name: "Cape Verde", cca2: "CV", flag: "🇨🇻", code: "238" },
  { name: "Costa Rica", cca2: "CR", flag: "🇨🇷", code: "506" },
  { name: "Cuba", cca2: "CU", flag: "🇨🇺", code: "53" },
  { name: "Cyprus", cca2: "CY", flag: "🇨🇾", code: "357" },
  { name: "Czechia", cca2: "CZ", flag: "🇨🇿", code: "420" },
  { name: "Germany", cca2: "DE", flag: "🇩🇪", code: "49" },
  { name: "Djibouti", cca2: "DJ", flag: "🇩🇯", code: "253" },
  { name: "Dominica", cca2: "DM", flag: "🇩🇲", code: "1767" },
  { name: "Denmark", cca2: "DK", flag: "🇩🇰", code: "45" },
  { name: "Dominican Republic", cca2: "DO", flag: "🇩🇴", code: "1809" },
  { name: "Algeria", cca2: "DZ", flag: "🇩🇿", code: "213" },
  { name: "Ecuador", cca2: "EC", flag: "🇪🇨", code: "593" },
  { name: "Egypt", cca2: "EG", flag: "🇪🇬", code: "20" },
  { name: "Eritrea", cca2: "ER", flag: "🇪🇷", code: "291" },
  { name: "Spain", cca2: "ES", flag: "🇪🇸", code: "34" },
  { name: "Estonia", cca2: "EE", flag: "🇪🇪", code: "372" },
  { name: "Ethiopia", cca2: "ET", flag: "🇪🇹", code: "251" },
  { name: "Finland", cca2: "FI", flag: "🇫🇮", code: "358" },
  { name: "Fiji", cca2: "FJ", flag: "🇫🇯", code: "679" },
  { name: "France", cca2: "FR", flag: "🇫🇷", code: "33" },
  { name: "Micronesia", cca2: "FM", flag: "🇫🇲", code: "691" },
  { name: "Gabon", cca2: "GA", flag: "🇬🇦", code: "241" },
  { name: "United Kingdom", cca2: "GB", flag: "🇬🇧", code: "44" },
  { name: "Georgia", cca2: "GE", flag: "🇬🇪", code: "995" },
  { name: "Ghana", cca2: "GH", flag: "🇬🇭", code: "233" },
  { name: "Guinea", cca2: "GN", flag: "🇬🇳", code: "224" },
  { name: "Gambia", cca2: "GM", flag: "🇬🇲", code: "220" },
  { name: "Guinea-Bissau", cca2: "GW", flag: "🇬🇼", code: "245" },
  { name: "Equatorial Guinea", cca2: "GQ", flag: "🇬🇶", code: "240" },
  { name: "Greece", cca2: "GR", flag: "🇬🇷", code: "30" },
  { name: "Grenada", cca2: "GD", flag: "🇬🇩", code: "1473" },
  { name: "Guatemala", cca2: "GT", flag: "🇬🇹", code: "502" },
  { name: "Guyana", cca2: "GY", flag: "🇬🇾", code: "592" },
  { name: "Honduras", cca2: "HN", flag: "🇭🇳", code: "504" },
  { name: "Croatia", cca2: "HR", flag: "🇭🇷", code: "385" },
  { name: "Haiti", cca2: "HT", flag: "🇭🇹", code: "509" },
  { name: "Hungary", cca2: "HU", flag: "🇭🇺", code: "36" },
  { name: "Indonesia", cca2: "ID", flag: "🇮🇩", code: "62" },
  { name: "India", cca2: "IN", flag: "🇮🇳", code: "91" },
  { name: "Ireland", cca2: "IE", flag: "🇮🇪", code: "353" },
  { name: "Iran", cca2: "IR", flag: "🇮🇷", code: "98" },
  { name: "Iraq", cca2: "IQ", flag: "🇮🇶", code: "964" },
  { name: "Iceland", cca2: "IS", flag: "🇮🇸", code: "354" },
  { name: "Israel", cca2: "IL", flag: "🇮🇱", code: "972" },
  { name: "Italy", cca2: "IT", flag: "🇮🇹", code: "39" },
  { name: "Jamaica", cca2: "JM", flag: "🇯🇲", code: "1876" },
  { name: "Jordan", cca2: "JO", flag: "🇯🇴", code: "962" },
  { name: "Japan", cca2: "JP", flag: "🇯🇵", code: "81" },
  { name: "Kazakhstan", cca2: "KZ", flag: "🇰🇿", code: "76" },
  { name: "Kenya", cca2: "KE", flag: "🇰🇪", code: "254" },
  { name: "Kyrgyzstan", cca2: "KG", flag: "🇰🇬", code: "996" },
  { name: "Cambodia", cca2: "KH", flag: "🇰🇭", code: "855" },
  { name: "Kiribati", cca2: "KI", flag: "🇰🇮", code: "686" },
  { name: "Saint Kitts and Nevis", cca2: "KN", flag: "🇰🇳", code: "1869" },
  { name: "South Korea", cca2: "KR", flag: "🇰🇷", code: "82" },
  { name: "Kuwait", cca2: "KW", flag: "🇰🇼", code: "965" },
  { name: "Laos", cca2: "LA", flag: "🇱🇦", code: "856" },
  { name: "Lebanon", cca2: "LB", flag: "🇱🇧", code: "961" },
  { name: "Liberia", cca2: "LR", flag: "🇱🇷", code: "231" },
  { name: "Libya", cca2: "LY", flag: "🇱🇾", code: "218" },
  { name: "Saint Lucia", cca2: "LC", flag: "🇱🇨", code: "1758" },
  { name: "Liechtenstein", cca2: "LI", flag: "🇱🇮", code: "423" },
  { name: "Sri Lanka", cca2: "LK", flag: "🇱🇰", code: "94" },
  { name: "Lesotho", cca2: "LS", flag: "🇱🇸", code: "266" },
  { name: "Lithuania", cca2: "LT", flag: "🇱🇹", code: "370" },
  { name: "Luxembourg", cca2: "LU", flag: "🇱🇺", code: "352" },
  { name: "Latvia", cca2: "LV", flag: "🇱🇻", code: "371" },
  { name: "Morocco", cca2: "MA", flag: "🇲🇦", code: "212" },
  { name: "Monaco", cca2: "MC", flag: "🇲🇨", code: "377" },
  { name: "Moldova", cca2: "MD", flag: "🇲🇩", code: "373" },
  { name: "Madagascar", cca2: "MG", flag: "🇲🇬", code: "261" },
  { name: "Maldives", cca2: "MV", flag: "🇲🇻", code: "960" },
  { name: "Mexico", cca2: "MX", flag: "🇲🇽", code: "52" },
  { name: "Marshall Islands", cca2: "MH", flag: "🇲🇭", code: "692" },
  { name: "Macedonia", cca2: "MK", flag: "🇲🇰", code: "389" },
  { name: "Mali", cca2: "ML", flag: "🇲🇱", code: "223" },
  { name: "Malta", cca2: "MT", flag: "🇲🇹", code: "356" },
  { name: "Myanmar", cca2: "MM", flag: "🇲🇲", code: "95" },
  { name: "Montenegro", cca2: "ME", flag: "🇲🇪", code: "382" },
  { name: "Mongolia", cca2: "MN", flag: "🇲🇳", code: "976" },
  { name: "Mozambique", cca2: "MZ", flag: "🇲🇿", code: "258" },
  { name: "Mauritania", cca2: "MR", flag: "🇲🇷", code: "222" },
  { name: "Mauritius", cca2: "MU", flag: "🇲🇺", code: "230" },
  { name: "Malawi", cca2: "MW", flag: "🇲🇼", code: "265" },
  { name: "Malaysia", cca2: "MY", flag: "🇲🇾", code: "60" },
  { name: "Namibia", cca2: "NA", flag: "🇳🇦", code: "264" },
  { name: "Niger", cca2: "NE", flag: "🇳🇪", code: "227" },
  { name: "Nigeria", cca2: "NG", flag: "🇳🇬", code: "234" },
  { name: "Nicaragua", cca2: "NI", flag: "🇳🇮", code: "505" },
  { name: "Netherlands", cca2: "NL", flag: "🇳🇱", code: "31" },
  { name: "Norway", cca2: "NO", flag: "🇳🇴", code: "47" },
  { name: "Nepal", cca2: "NP", flag: "🇳🇵", code: "977" },
  { name: "Nauru", cca2: "NR", flag: "🇳🇷", code: "674" },
  { name: "New Zealand", cca2: "NZ", flag: "🇳🇿", code: "64" },
  { name: "Oman", cca2: "OM", flag: "🇴🇲", code: "968" },
  { name: "Pakistan", cca2: "PK", flag: "🇵🇰", code: "92" },
  { name: "Panama", cca2: "PA", flag: "🇵🇦", code: "507" },
  { name: "Peru", cca2: "PE", flag: "🇵🇪", code: "51" },
  { name: "Philippines", cca2: "PH", flag: "🇵🇭", code: "63" },
  { name: "Palau", cca2: "PW", flag: "🇵🇼", code: "680" },
  { name: "Papua New Guinea", cca2: "PG", flag: "🇵🇬", code: "675" },
  { name: "Poland", cca2: "PL", flag: "🇵🇱", code: "48" },
  { name: "North Korea", cca2: "KP", flag: "🇰🇵", code: "850" },
  { name: "Portugal", cca2: "PT", flag: "🇵🇹", code: "351" },
  { name: "Paraguay", cca2: "PY", flag: "🇵🇾", code: "595" },
  { name: "Qatar", cca2: "QA", flag: "🇶🇦", code: "974" },
  { name: "Romania", cca2: "RO", flag: "🇷🇴", code: "40" },
  { name: "Russia", cca2: "RU", flag: "🇷🇺", code: "7" },
  { name: "Rwanda", cca2: "RW", flag: "🇷🇼", code: "250" },
  { name: "Saudi Arabia", cca2: "SA", flag: "🇸🇦", code: "966" },
  { name: "Sudan", cca2: "SD", flag: "🇸🇩", code: "249" },
  { name: "Senegal", cca2: "SN", flag: "🇸🇳", code: "221" },
  { name: "Singapore", cca2: "SG", flag: "🇸🇬", code: "65" },
  { name: "Solomon Islands", cca2: "SB", flag: "🇸🇧", code: "677" },
  { name: "Sierra Leone", cca2: "SL", flag: "🇸🇱", code: "232" },
  { name: "El Salvador", cca2: "SV", flag: "🇸🇻", code: "503" },
  { name: "San Marino", cca2: "SM", flag: "🇸🇲", code: "378" },
  { name: "Somalia", cca2: "SO", flag: "🇸🇴", code: "252" },
  { name: "Serbia", cca2: "RS", flag: "🇷🇸", code: "381" },
  { name: "South Sudan", cca2: "SS", flag: "🇸🇸", code: "211" },
  { name: "São Tomé and Príncipe", cca2: "ST", flag: "🇸🇹", code: "239" },
  { name: "Suriname", cca2: "SR", flag: "🇸🇷", code: "597" },
  { name: "Slovakia", cca2: "SK", flag: "🇸🇰", code: "421" },
  { name: "Slovenia", cca2: "SI", flag: "🇸🇮", code: "386" },
  { name: "Sweden", cca2: "SE", flag: "🇸🇪", code: "46" },
  { name: "Swaziland", cca2: "SZ", flag: "🇸🇿", code: "268" },
  { name: "Seychelles", cca2: "SC", flag: "🇸🇨", code: "248" },
  { name: "Syria", cca2: "SY", flag: "🇸🇾", code: "963" },
  { name: "Chad", cca2: "TD", flag: "🇹🇩", code: "235" },
  { name: "Togo", cca2: "TG", flag: "🇹🇬", code: "228" },
  { name: "Thailand", cca2: "TH", flag: "🇹🇭", code: "66" },
  { name: "Tajikistan", cca2: "TJ", flag: "🇹🇯", code: "992" },
  { name: "Turkmenistan", cca2: "TM", flag: "🇹🇲", code: "993" },
  { name: "Timor-Leste", cca2: "TL", flag: "🇹🇱", code: "670" },
  { name: "Tonga", cca2: "TO", flag: "🇹🇴", code: "676" },
  { name: "Trinidad and Tobago", cca2: "TT", flag: "🇹🇹", code: "1868" },
  { name: "Tunisia", cca2: "TN", flag: "🇹🇳", code: "216" },
  { name: "Turkey", cca2: "TR", flag: "🇹🇷", code: "90" },
  { name: "Tuvalu", cca2: "TV", flag: "🇹🇻", code: "688" },
  { name: "Tanzania", cca2: "TZ", flag: "🇹🇿", code: "255" },
  { name: "Uganda", cca2: "UG", flag: "🇺🇬", code: "256" },
  { name: "Ukraine", cca2: "UA", flag: "🇺🇦", code: "380" },
  { name: "Uruguay", cca2: "UY", flag: "🇺🇾", code: "598" },
  { name: "United States", cca2: "US", flag: "🇺🇸", code: "1" },
  { name: "Uzbekistan", cca2: "UZ", flag: "🇺🇿", code: "998" },
  { name: "Vatican City", cca2: "VA", flag: "🇻🇦", code: "3906698" },
  {
    name: "Saint Vincent and the Grenadines",
    cca2: "VC",
    flag: "🇻🇨",
    code: "1784",
  },
  { name: "Venezuela", cca2: "VE", flag: "🇻🇪", code: "58" },
  { name: "Vietnam", cca2: "VN", flag: "🇻🇳", code: "84" },
  { name: "Vanuatu", cca2: "VU", flag: "🇻🇺", code: "678" },
  { name: "Samoa", cca2: "WS", flag: "🇼🇸", code: "685" },
  { name: "Yemen", cca2: "YE", flag: "🇾🇪", code: "967" },
  { name: "South Africa", cca2: "ZA", flag: "🇿🇦", code: "27" },
  { name: "Zambia", cca2: "ZM", flag: "🇿🇲", code: "260" },
  { name: "Zimbabwe", cca2: "ZW", flag: "🇿🇼", code: "263" },
];
