import { Task } from "./types";

export const defaultTasks: Task[] = [
    {
        id: "1",
        columnId: "pdfs",
        content: "Issue #79: Implement authentication system",
        userName: "Sujal",
        role: "Developer",
        userpfp: "./sujal-pfp.png",
    },
    {
        id: "2",
        columnId: "spdfs",
        content: "Design user interface for the dashboard",
        userName: "Soham",
        role: "Designer",
        userpfp: "./soham-pfp.jpg",
    },
    {
        id: "3",
        columnId: "spdfs",
        content: "Define product roadmap for the next quarter",
        userName: "Surabhi",
        role: "Product Manager",
        userpfp: "./saniyaa-pfp.png",
    },
    {
        id: "4",
        columnId: "pdfs",
        content: "Issue #82: Optimize database queries for performance",
        userName: "Srinath",
        role: "Developer",
        userpfp: "./anish-pfp.jpg",
    },
    {
        id: "5",
        columnId: "done",
        content: "Create wireframes for new feature",
        userName: "Soham",
        role: "Designer",
        userpfp: "./soham-pfp.jpg",
    },
    {
        id: "6",
        columnId: "todo",
        content: "Gather user feedback on current features",
        userName: "Surabhi",
        role: "Product Manager",
        userpfp: "./saniyaa-pfp.png",
    },
    {
        id: "7",
        columnId: "done",
        content: "Issue #85: Fix bugs reported in the last sprint",
        userName: "Srinath",
        role: "Developer",
        userpfp: "./anish-pfp.jpg",
    },
    {
        id: "8",
        columnId: "done",
        content: "Create visual assets for marketing campaign",
        userName: "Soham",
        role: "Designer",
        userpfp: "./soham-pfp.jpg",
    },
    {
        id: "9",
        columnId: "todo",
        content: "Prioritize and refine the product backlog",
        userName: "Surabhi",
        role: "Product Manager",
        userpfp: "g",
    },
    {
        id: "10",
        columnId: "todo",
        content: "Issue #88: Implement new feature according to specifications",
        userName: "Srinath",
        role: "Developer",
        userpfp: "",
    },
];
